---
- name: "Install Homebrew TAP Packages"
  community.general.homebrew_tap:
    name: "{{ packages }}"
  vars:
    packages:
      - 'adoptopenjdk/openjdk'
      - 'hashicorp/tap'
      - 'heroku/brew'

- name: "Install Homebrew Packages"
  community.general.homebrew:
    name: "{{ packages }}"
  vars:
    packages:
      # - 'ccze'
      # - 'freerdp'
      # - 'tfenv'
      - 'azure-cli'
      - 'boot2docker'
      - 'certbot'
      - 'consul'
      - 'curl'
      - 'docker-compose'
      - 'docker-machine'
      - 'drone-cli'
      - 'gh'
      - 'git'
      - 'git-crypt'
      - 'git-flow'
      - 'git-ftp'
      - 'git-lfs'
      - 'glab'
      - 'istioctl'
      - 'k3d'
      - 'k9s'
      - 'kops'
      - 'krew'
      - 'kubectl'
      - 'kubectx'
      - 'kubernetes-helm'
      - 'kubeseal'
      - 'kubespy'
      - 'kubie'
      - 'libmagic'
      - 'mcrypt'
      - 'minikube'
      - 'nano'
      - 'ncdu'
      - 'netdata'
      - 'nmap'
      - 'nomad'
      - 'nvm'
      - 'openfortivpn'
      - 'openvpn'
      - 'packer'
      - 'php'
      - 'podman'
      - 'pre-commit'
      - 'pulumi'
      - 'rancher-compose'
      - 'rdesktop'
      - 'skaffold'
      - 'skopeo'
      - 'sqlite'
      - 'sshuttle'
      - 'stern'
      - 'stunnel'
      - 'syncthing'
      - 'terraform'
      - 'terraform-docs'
      - 'terraform-inventory'
      - 'terraformer'
      - 'terragrunt'
      - 'terrascan'
      - 'tmux'
      - 'universal-ctags'
      - 'vault'
      - 'velero'
    state: present
    update_homebrew: yes
    upgrade_all: yes
  register: brew_devops_result
  ignore_errors: true
  # failed_when: "'Error:' in brew_devops_result.stdout"

- name: "Install Homebrew Cask Packages"
  community.general.homebrew_cask:
    name: "{{ packages }}"
  vars:
    packages:
      # - 'atom'
      # - 'forticlient'
      # - 'keepassxc'
      # - 'lastpass'
      # - 'slack'
      # - 'soapui'
      # - 'sublime-text'
      # - 'teamviewer'
      - 'adoptopenjdk'
      - 'android-platform-tools'
      - 'android-studio'
      - 'azure-data-studio'
      - 'chromedriver'
      - 'cryptr'
      - 'docker'
      - 'google-cloud-sdk'
      - 'gpg-suite'
      - 'ibm-cloud-cli'
      - 'insomnia'
      - 'intellij-idea-ce'
      - 'iterm2'
      - 'meld'
      - 'microsoft-azure-storage-explorer'
      - 'miniconda'
      - 'mysqlworkbench'
      - 'openlens'
      - 'pgadmin4'
      - 'postman'
      - 'robo-3t'
      - 'vagrant'
      - 'vagrant-manager'
      - 'virtualbox'
      - 'virtualbox-extension-pack'
      - 'visual-studio-code'
      - 'wine-stable'
      - 'xquartz'
    state: present
    upgrade_all: yes
    update_homebrew: yes
  register: brew_cask_devops_result
  ignore_errors: true
  # failed_when: "'Error:' in brew_cask_devops_result.stdout"

